### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Xonshiz** [puilp0502/comic-downloader#2]
I've been trying to use this. What kind of input do you need?
I tried entering the whole url, error...
So, I entered the TitleID, got me good.
Then I entered `1` for start and it went well,
but then I entered `10` for End, showed me an EOF error

**Comment by puilp0502** [comment]
Can you provide a full stack trace?

**Comment by Xonshiz** [comment]
I made a little change in the script, first check that. And now after changing stuff, this is the output.


```
C:\Users\UserName\Desktop\comic-downloader-master>naver.py
Input url:http://comic.naver.com/webtoon/detail.nhn?titleId=654817&no=72&weekday=tue
Start[1]:1
End[unlimited]:2
Title Id: 654817
Base URL: http://comic.naver.com/webtoon/detail.nhn?titleId=654817&no=
Episode 1
Traceback (most recent call last):
  File "C:\Users\UserName\Desktop\comic-downloader-master\naver.py", line 69, in <module>
    except ConnectionRefusedError:
NameError: name 'ConnectionRefusedError' is not defined

C:\Users\UserName\Desktop\comic-downloader-master>
```

**Comment by puilp0502** [comment]
I guess that's due to Python 2.x. The script should work on Python 3.

**Comment by Xonshiz** [comment]
Just tried on Python3, and it won't encode the characs. Output here : 

```

C:\Users\UserName\Desktop\comic-downloader-master>py -3 naver.py
Input url:http://comic.naver.com/webtoon/detail.nhn?titleId=654817&no=72&weekday=tue
Start[1]:1
End[unlimited]:
Title Id: 654817
Base URL: http://comic.naver.com/webtoon/detail.nhn?titleId=654817&no=
Episode 1
Traceback (most recent call last):
  File "naver.py", line 61, in <module>
    print("Downloading "+author_id + "'s " + comic_name)
  File "C:\Pythons\Python3.5\lib\encodings\cp437.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 31-32: character maps to <undefined>
```

**Comment by puilp0502** [comment]
Weird... I don't get the same error in my system.  
Can you tell me your system's locale?

**Comment by Xonshiz** [comment]
English(India)... what's yours?

**Comment by puilp0502** [comment]
It appears that the console is the problem, not the python. ([ref](http://stackoverflow.com/a/14284404) here)  
You might try using `chcp 65001`.
