### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by jrdp18** [puilp0502/comic-downloader#4]
Hi!

I'm a Python layman. I've got Python 3 installed and tried running it thru Windows cmd. I get `ImportError: No module named 'requests'`. What should I do next?

Thanks!

**Comment by puilp0502** [comment]
It's an external module. You have to install it with [pip](https://pip.pypa.io/en/stable/).
In command prompt enter:
```
pip install requests
```
And you should be good to go.

**Comment by jrdp18** [comment]
I got unicode error after this

```
C:\Users\xxxx\Downloads>naver.py
Input url:http://comic.naver.com/webtoon/detail.nhn?titleId=58526
Start[1]:1
End[unlimited]:2
Title Id: 58526
Base URL: http://comic.naver.com/webtoon/detail.nhn?titleId=58526&no=
Episode 1
Traceback (most recent call last):
  File "C:\Users\xxxx\Downloads\naver.py", line 61, in <module>
    print("Downloading "+author_id + "'s " + comic_name)
UnicodeEncodeError: 'cp932' codec can't encode character '\uc7ac' in position 31: illegal multibyte sequence

C:\Users\xxxx\Downloads>
```

**Comment by puilp0502** [comment]
Can you try typing `chcp 65001` into cmd and running the script again?

**Comment by jrdp18** [comment]
```
Active code page: 65001

C:\Users\xxxx\Downloads>naver.py
Input url:http://comic.naver.com/webtoon/detail.nhn?titleId=58526
Start[1]:1
End[unlimited]:2
Title Id: 58526
Base URL: http://comic.naver.com/webtoon/detail.nhn?titleId=58526&no=
Episode 1
                         ìž¬í™œìš©'s ì—°ë¯¼ì˜ êµ´ë ˆ
     1
Traceback (most recent call last):
  File "C:\Users\xxxx\Downloads\naver.py", line 67, in <module>
    download_file(image_url, author_id+"/"+comic_name+"/"+str(episode),detail_url)
  File "C:\Users\xxxx\Downloads\naver.py", line 9, in download_file
    os.makedirs(foldername)
  File "C:\Python34\lib\os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "C:\Python34\lib\os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "C:\Python34\lib\os.py", line 237, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '\r                \t ìž¬í™œìš©'

C:\Users\xxxx\Downloads>
```

**Comment by puilp0502** [comment]
You're not using up-to-date version. Please pull the repository again.

**Comment by jrdp18** [comment]
Works now, thank you very much!
